######################################################################
# Automatically generated by qmake (3.0) ?? ???? 16 16:20:33 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++11

ragel.output = ${QMAKE_FILE_IN_PATH}/${QMAKE_FILE_IN_BASE}    # output file (input filename without .rl)
ragel.input = RAGEL_FILES         # list of input files
ragel.commands = ragel ${QMAKE_FILE_IN} -o ${QMAKE_FILE_OUT}    #command
ragel.variable_out = SOURCES    # where output files should be placed
ragel.name = RAGEL    # name (for internal qmake usage)

QMAKE_EXTRA_COMPILERS += ragel

RAGEL_FILES += ../hterm_core/htcodec/htcodec_iso14230.cpp.rl

# Input
SOURCES += test_htcodec_iso14230.cpp

SOURCES += \
    ../hterm_core/htdatamsg/htdatapart.cpp \
    ../hterm_core/htdatamsg/htdatamsg.cpp


HEADERS += ../hterm_core/htdatamsg/htdatapart.h \
    ../hterm_core/htcodec/htcodec.h \
    ../hterm_core/htcodec/htcodec_iso14230.h
    
INCLUDEPATH += ../hterm_core/htcodec \
               ../hterm_core/htdatamsg \
               ../hterm_code/htdatasrc
               


