######################################################################
# Automatically generated by qmake (3.0) ?? ???? 16 16:20:33 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++11

include(../common/ragel.pri)

SRC_ROOT = ../..

RAGEL_FILES += ../../hterm_core/htcodec/htcodec_iso14230.cpp.rl

# Input
SOURCES += ../../test/test_htcodec_iso14230.cpp

SOURCES += \
    ../../hterm_core/htdatamsg/htdatapart.cpp \
    ../../hterm_core/htdatamsg/htdatamsg.cpp


HEADERS += ../../hterm_core/htdatamsg/htdatapart.h \
    ../../hterm_core/htcodec/htcodec.h \
    ../../hterm_core/htcodec/htcodec_iso14230.h
    
INCLUDEPATH += ../../hterm_core/htcodec \
               ../../hterm_core/htdatamsg \
               ../../hterm_code/htdatasrc



