/*******************************************************************************
 *   Description:   TODO
 *
 ******************************************************************************/

#ifndef _BT_EVENT_DATA_MSG_H
#define _BT_EVENT_DATA_MSG_H

/*******************************************************************************
 * INCLUDED FILES
 ******************************************************************************/

#include <QObject>

#include "bt_event.h"
#include "bt_datamsg.h"


/*******************************************************************************
 * CLASS DECLARATION
 ******************************************************************************/

namespace BTCore {
    class EventDataMsg;
}


class BTCore::EventDataMsg : public BTCore::Event
{
    /****************************************************************************
     * TYPES
     ***************************************************************************/

public:

    /**
     * Direction of the message: Rx or Tx.
     */
    enum class Direction {
        RX,
        TX,
    };


    /****************************************************************************
     * CONSTRUCTOR, DESTRUCTOR
     ***************************************************************************/
public:

    /**
     * @param msg
     *      Message that this event is about
     * @param dir
     *      Direction of the message: Rx or Tx. See `#Direction`.
     * @param descr
     *      Optional. Represents additional description about the message.
     *      For example, when the message is generated by some handler,
     *      the handler title is set here.
     */
    EventDataMsg(
            const DataMsg &msg,
            Direction dir,
            QString descr = ""
            );


    /****************************************************************************
     * PRIVATE DATA
     ***************************************************************************/
private:

    DataMsg msg;
    Direction dir;
    QString descr;


    /****************************************************************************
     * STATIC METHODS
     ***************************************************************************/

    /****************************************************************************
     * METHODS
     ***************************************************************************/
public:

    const DataMsg getMsg() const;
    Direction getDir() const;
    QString getDescr() const;

    virtual const QString toString() const override;
    virtual void accept(EventVisitor &visitor) override;


    /****************************************************************************
     * SIGNALS, SLOTS
     ***************************************************************************/

};


#endif // _BT_EVENT_DATA_MSG_H
