######################################################################
# Automatically generated by qmake (3.0) ?? ???? 16 16:20:33 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = hterm-test

include(../common/appl_common.pri)
include(../common/hterm_core.pri)

# Input

SOURCES += ../../src/test/test_htcodec_iso14230.cpp
SOURCES += ../../src/test/test_main.cpp

HEADERS += ../../src/test/test_htcodec_iso14230.h



