######################################################################
# Automatically generated by qmake (3.0) ?? ???? 16 16:20:33 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = hterm-test

include(../common/appl_common.pri)
include(../common/htcore.pri)

# Input

SOURCES += \
   ../../src/util/my_util.cpp \
   ../../src/test/test_htcodec_iso14230.cpp \
   ../../src/test/test_htdatamsg.cpp \
   ../../src/test/test_main.cpp \


HEADERS += \
   ../../src/util/my_util.h \
   ../../src/test/test_htcodec_iso14230.h \
   ../../src/test/test_htdatamsg.h \


INCLUDEPATH += \
   ../../src/util \


